# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy ARM Template'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'yourServiceConnectionName'
    subscriptionId: 'f24b8432-ae1f-456b-a6b5-1bbcf729bf8c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'TestGroup'
    location: 'centralus'
    templateLocation: 'Linked artifact'
    csmFile: 'TestArmTemplate.json'
    csmParametersFile: 'path/to/your/arm-parameters.json'